<a href="https://colab.research.google.com/github/Satyabratadas/GeoEmerge_hackathon/blob/master/analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd                           # For working with data
pd.set_option("display.max_columns", None)    # Lets us see all columns of the data instead of just a preview
import geopandas as gpd                       # For working with spatial data
import numpy as np                            # For working with numbers
import matplotlib.pyplot as plt               # For making graphs
from datetime import date                     # For formatting dates
from PIL import Image                         # For getting and displaying images from links
import requests                               # For getting information from links
from io import BytesIO                        # For working with types of input and output

import seaborn as sns
import folium
from folium.plugins import HeatMap


end_date = "2026-01-31"

data = gpd.read_file(f"https://api.globe.gov/search/v1/measurement/?protocols=mosquito_habitat_mapper&datefield=measuredDate&startdate=2018-01-01&enddate={end_date}&geojson=TRUE&sample=FALSE")

In [18]:
#mosquito = gpd.read_file('https://github.com/geo-di-lab/emerge-lessons/raw/refs/heads/main/docs/data/globe_mosquito.zip')
land_cover = gpd.read_file(f"https://api.globe.gov/search/v1/measurement/?protocols=land_covers&datefield=measuredDate&startdate=2018-01-01&enddate={end_date}&geojson=TRUE&sample=FALSE")

In [19]:
land_cover

,countryCode,countryName,elevation,landcoversDataSource,landcoversDownwardCaption,landcoversDownwardExtraData,landcoversDownwardPhotoUrl,landcoversDryGround,landcoversEastCaption,landcoversEastClassifications,landcoversEastExtraData,landcoversEastPhotoUrl,landcoversFeature1Caption,landcoversFeature1ExtraData,landcoversFeature1PhotoUrl,landcoversFeature2Caption,landcoversFeature2ExtraData,landcoversFeature2PhotoUrl,landcoversFeature3Caption,landcoversFeature3ExtraData,landcoversFeature3PhotoUrl,landcoversFeature4Caption,landcoversFeature4ExtraData,landcoversFeature4PhotoUrl,landcoversFieldNotes,landcoversGlobeTeams,landcoversLandCoverId,landcoversLeavesOnTrees,landcoversLocationAccuracyM,landcoversLocationMethod,landcoversMeasuredAt,landcoversMeasurementElevation,landcoversMeasurementLatitude,landcoversMeasurementLongitude,landcoversMucCode,landcoversMucDescription,landcoversMucDetails,landcoversMuddy,landcoversNorthCaption,landcoversNorthClassifications,landcoversNorthExtraData,landcoversNorthPhotoUrl,landcoversRainingSnowing,landcoversSnowIce,landcoversSouthCaption,landcoversSouthClassifications,landcoversSouthExtraData,landcoversSouthPhotoUrl,landcoversStandingWater,landcoversUpwardCaption,landcoversUpwardExtraData,landcoversUpwardPhotoUrl,landcoversUserid,landcoversWestCaption,landcoversWestClassifications,landcoversWestExtraData,landcoversWestPhotoUrl,organizationId,organizationName,protocol,siteId,siteName,geometry
0,USA,United States,6.9,GLOBE Observer App,null,null,pending approval,false,null,null,null,pending approval,null,null,null,null,null,null,null,null,null,null,null,null,(none),None,89459,true,52,automatic,2026-01-31 03:33:00.000,7.3,21.3247,-158.0259,null,null,,true,null,null,null,https://data.globe.gov/system/photos/2026/01/3...,true,false,null,null,null,pending approval,false,null,null,https://data.globe.gov/system/photos/2026/01/3...,178265728,null,null,null,pending approval,17043304,United States of America Citizen Science,land_covers,408348,04QFJ010583,POINT (-158.0261 21.32383)
1,USA,United States,2.9,GLOBE Observer App,null,null,pending approval,false,null,null,null,pending approval,null,null,null,null,null,null,null,null,null,null,null,null,(none),None,89458,true,32,automatic,2026-01-31 03:02:00.000,4.3,21.3173,-157.8621,null,null,,false,null,null,null,pending approval,true,false,null,null,null,pending approval,false,null,null,https://data.globe.gov/system/photos/2026/01/3...,178386707,null,null,null,pending approval,17043304,United States of America Citizen Science,land_covers,409681,04QFJ180576,POINT (-157.86225 21.31648)
2,USA,United States,265.1,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2026/01/3...,false,null,null,null,pending approval,null,null,null,null,null,null,null,null,null,null,null,null,(none),None,89457,true,25,automatic,2026-01-31 00:19:00.000,271,21.4798,-157.9967,null,null,,true,null,null,null,pending approval,true,false,null,null,null,pending approval,false,null,null,https://data.globe.gov/system/photos/2026/01/3...,178357780,null,null,null,pending approval,17043304,United States of America Citizen Science,land_covers,409676,04QFJ039755,POINT (-157.99708 21.47905)
3,USA,United States,7.9,GLOBE Data Entry Site Definition,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,None,89460,null,null,null,2026-01-31 03:49:22.993,None,None,None,M9,Urban,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,17043304,United States of America Citizen Science,land_covers,409682,Park,POINT (-158.0261 21.325)
4,USA,United States,159.2,GLOBE Observer App,null,null,pending approval,false,null,"60% MUC 43 [Herbaceous/Grassland, Short Grass]...",null,https://data.globe.gov/system/photos/2026/01/3...,null,null,null,null,null,null,null,null,null,null,null,null,(none),[Oregon State University GEOGRAPHY],89456,true,12,automatic,2026-01-31 00:26:00.000,152.7,47.428,-122.0285,M43,"Herbaceous/Grassland, Short Grass",,true,null,"70% MUC 43 [Herbaceous/Grassland, Short Grass]...",null,https://data.globe.gov/system/photos/2026/01/3...,true,false,null,"50% MUC 43 [Herbaceous/Grassland, Short Grass]...",null,pending approval,false,null,null,https://data.globe.gov/system/photos/2026/01/3...,178086139,null,"80% MUC 43 [Herbaceous/Grassland, Short Grass]...",null,pending approval,17043304,United States of America Citizen Science,land_covers,409675,10TET732531,POINT (-122.0294 47.42724)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61158,HRV,Croatia,151.0,GLOBE Data Entry Site Definition,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,None,20325,null,null,null,2018-01-16 19:45:36.392,None,None,None,M1211,"Woodland, Mainly Deciduous, Drought-Deciduous,...",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,177974,II. osnovna skola Cakovec,land_covers,104400,Muršćak-biometrija,POINT (16.52 46.46)
61159,OMN,Oman,584.0,GLOBE Data Entry Site Definition,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,None,20324,null,null,null,2018-01-16 12:52:15.524,None,None,None,M823,"Cultivated Land, Non-Agriculture, Cemeteries",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,23062994,Elayet feda basic school,land_covers,104390,yanqul park,POINT (56.43 23.43)
61160,OMN,Oman,27.0,GLOBE Data Entry Site Definition,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,None,20322,null,null,null,2018-01-03 22:00:19.250,None,None,None,M812,"Cultivated Land, Agriculture, Orchard and Hort...",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,23061684,Al duqom basic school,land_covers,101771,ALduqm shcool,POINT (57.37 19.37)
61161,OMN,Oman,27.0,GLOBE Data Entry Site Definition,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,None,20321,null,null,null,2018-01-03 21:57:54.342,None,None,None,M812,"Cultivated Land, Agriculture, Orchard and Hort...",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,23061684,Al duqom basic school,land_covers,101771,ALduqm shcool,POINT (57.37 19.37)
61162,OMN,Oman,0.0,GLOBE Data Entry Site Definition,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,None,20320,null,null,null,2018-01-01 08:47:12.483,None,None,None,M8,Cultivated Land,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,36736232,Madira Pasic School,land_covers,104036,MADERA BASIC SCHOOL,POINT (58.167 21.0717)

In [36]:
florida_only = land_cover[
    (land_cover["countryCode"] == "USA") & (land_cover.geometry.x.between(-87.7, -79.6)) & (land_cover.geometry.y.between(24.4, 31.1))
].copy()

In [40]:
florida_only.shape

(690, 63)

In [23]:
florida_only

,countryCode,countryName,elevation,landcoversDataSource,landcoversDownwardCaption,landcoversDownwardExtraData,landcoversDownwardPhotoUrl,landcoversDryGround,landcoversEastCaption,landcoversEastClassifications,landcoversEastExtraData,landcoversEastPhotoUrl,landcoversFeature1Caption,landcoversFeature1ExtraData,landcoversFeature1PhotoUrl,landcoversFeature2Caption,landcoversFeature2ExtraData,landcoversFeature2PhotoUrl,landcoversFeature3Caption,landcoversFeature3ExtraData,landcoversFeature3PhotoUrl,landcoversFeature4Caption,landcoversFeature4ExtraData,landcoversFeature4PhotoUrl,landcoversFieldNotes,landcoversGlobeTeams,landcoversLandCoverId,landcoversLeavesOnTrees,landcoversLocationAccuracyM,landcoversLocationMethod,landcoversMeasuredAt,landcoversMeasurementElevation,landcoversMeasurementLatitude,landcoversMeasurementLongitude,landcoversMucCode,landcoversMucDescription,landcoversMucDetails,landcoversMuddy,landcoversNorthCaption,landcoversNorthClassifications,landcoversNorthExtraData,landcoversNorthPhotoUrl,landcoversRainingSnowing,landcoversSnowIce,landcoversSouthCaption,landcoversSouthClassifications,landcoversSouthExtraData,landcoversSouthPhotoUrl,landcoversStandingWater,landcoversUpwardCaption,landcoversUpwardExtraData,landcoversUpwardPhotoUrl,landcoversUserid,landcoversWestCaption,landcoversWestClassifications,landcoversWestExtraData,landcoversWestPhotoUrl,organizationId,organizationName,protocol,siteId,siteName,geometry
602,USA,United States,51.2,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2026/01/0...,true,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 231, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 312, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 314, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,Standing decidusous broadleaf trees,"((compassData.heading: 169, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,Cutdown trees to west.,"[HTLC, OpeningTheAperture EarthAsArt, Oregon H...",88833,true,5,automatic,2026-01-02 19:47:00.000,48.3,28.6467,-81.7105,null,null,,false,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,false,false,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,false,null,null,https://data.globe.gov/system/photos/2026/01/0...,8267248,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,32402168,"College of Earth, Ocean, Atmospheric Sciences ...",land_covers,407606,17RMM305690,POINT (-81.71114 28.64624)
606,USA,United States,41.4,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2026/01/0...,true,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 287, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 67, compassData.horizon...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 155, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 227, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,Observation tower at tree canopy height. Everg...,"[HTLC, OpeningTheAperture EarthAsArt, Oregon H...",88836,true,5,automatic,2026-01-02 19:34:00.000,34.7,28.6474,-81.7085,null,null,,false,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,false,false,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,false,null,null,https://data.globe.gov/system/photos/2026/01/0...,8267248,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,32402168,"College of Earth, Ocean, Atmospheric Sciences ...",land_covers,407608,17RMM307691,POINT (-81.7091 28.64716)
607,USA,United States,41.4,GLOBE Observer App,null,null,null,true,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,Duplicate location with manual photos,"[HTLC, OpeningTheAperture EarthAsArt, Oregon H...",88835,true,4,automatic,2026-01-02 19:36:00.000,34.7,28.6474,-81.7085,null,null,,false,null,null,null,null,false,false,null,null,null,null,false,null,null,null,8267248,null,null,null,null,32402168,"College of Earth, Ocean, Atmospheric Sciences ...",land_covers,407608,17RMM307691,POINT (-81.7091 28.64716)
614,USA,United States,43.9,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2026/01/0...,true,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 328, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 231, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,Trail with whitish material,"((compassData.heading: 131, compassData.horizo...",https://data.globe.gov/system/photos/2026/01/0...,null,"((compassData.heading: 61, compassData.horizon...",https://data.globe.gov/system/photos/2026/01/0...,(none),"[HTLC, OpeningTheAperture EarthAsArt, Oregon H...",88834,true,5,automatic,2026-01-02 19:42:00.000,43.1,28.6472,-81.71,null,null,,false,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,false,false,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,false,null,null,https://data.globe.gov/system/photos/2026/01/0...,8267248,null,null,null,https://data.globe.gov/system/photos/2026/01/0...,32402168,"College of Earth, Ocean, Atmospheric Sciences ...",land_covers,407607,17RMM306691,POINT (-81.71012 28.64715)
707,USA,United States,2.1,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2025/12/2...,true,null,null,null,https://data.globe.gov/system/photos/2025/12/2...,null,null,null,null,null,null,null,null,null,null,null,null,(none),[NASA Response Mappers],88712,true,4,automatic,2025-12-23 19:58:00.000,2.2,25.6479,-80.3833,null,null,,false,null,null,null,https://data.globe.gov/system/photos/2025/12/2...,false,false,null,null,null,https://data.globe.gov/system/photos/2025/12/2...,false,null,null,https://data.globe.gov/system/photos/2025/12/2...,120475683,null,null,null,https://data.globe.gov/system/photos/2025/12/2...,17043304,United States of America Citizen Science,land_covers,394594,17RNJ619368,POINT (-80.38332 25.64757)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58144,USA,United States,14.4,GLOBE Observer App,,"(source: app, (compassData.heading: 147.638908...",https://data.globe.gov/system/photos/2019/03/2...,true,,"20% MUC 01 (n) [Trees, Closely Spaced, Evergre...","(source: app, (compassData.heading: 93.9896206...",https://data.globe.gov/system/photos/2019/03/2...,null,null,null,null,null,null,null,null,null,null,null,null,(none),None,22012,true,10,automatic,2019-03-21 16:46:00.000,8.1,29.9226,-81.4174,M92,"Urban, Commercial Property",,false,,"20% MUC 01 (n) [Trees, Closely Spaced, Evergre...","(source: app, (compassData.heading: 358.015319...",https://data.globe.gov/system/photos/2019/03/2...,false,false,,"20% MUC 01 (n) [Trees, Closely Spaced, Evergre...","(source: app, (compassData.heading: 177.494270...",https://data.globe.gov/system/photos/2019/03/2...,false,,"(source: app, (compassData.heading: 292.699996...",https://data.globe.gov/system/photos/2019/03/2...,24007076,,"10% MUC 01 (n) [Trees, Closely Spaced, Evergre...","(source: app, (compassData.heading: 271.356033...",https://data.globe.gov/system/photos/2019/03/2...,17043304,United States of America Citizen Science,land_covers,148173,17RMP597102,POINT (-81.41752 29.92186)
58235,USA,United States,3.7,GLOBE Observer App,,"(source: app, (compassData.heading: 186.175346...",https://data.globe.gov/system/photos/2019/03/1...,true,,null,"(source: app, (compassData.heading: 90.2919456...",https://data.globe.gov/system/photos/2019/03/1...,null,null,null,null,null,null,null,null,null,null,null,null,No recent or planned changes (except to possib...,None,2282,true,65,automatic,2019-03-16 16:33:00.000,8.1,29.961,-81.5346,null,null,,false,,null,"(source: app, (compassData.heading: 1.82150268...",https://data.globe.gov/system/photos/2019/03/1...,false,false,,null,"(source: app, (compassData.heading: 181.046768...",https://data.globe.gov/system/photos/2019/03/1...,false,,"(source: app, (compassData.heading: 169.329292...",https://data.globe.gov/system/photos/2019/03/1...,24007076,,null,"(source: app, (compassData.heading: 267.202651...",https://data.globe.gov/system/photos/2019/03/1...,17043304,United States of America Citizen Science,land_covers,104018,17RMP484145,POINT (-81.53479 29.96024)
58668,USA,United States,7.2,GLOBE Observer App,,"(source: app, (compassData.heading: 126.497680...",https://data.globe.gov/system/photos/2019/02/1...,true,,null,"(source: app, (compassData.heading: 93.4000549...",https://data.globe.gov/system/photos/2019/02/1...,null,null,null,null,null,null,null,null,null,null,null,null,(none),None,1913,true,null,manual,2019-02-19 12:29:00.000,-263.2,26.5935,-80.1683,null,null,,false,,null,"(source: app, (compassData.heading: 3.08322906...",https://data.globe.gov/system/photos/2019/02/1...,false,false,,null,"(source: app, (compassData.heading: 185.371124...",https://data.globe.gov/system/photos/2019/02/1...,false,,"(source: app, (compassData.heading: 38.3885955...",https://data.globe.gov/system/photos/2019/02/1...,27492755,,null,"(source: app, (compassData.heading: 271.863182...",https://data.globe.gov/system/photos/2019/02/1...,17043304,United States of America Citizen Science,land_covers,69761,17RNK828416,POINT (-80.16844 26.59276)
59825,USA,United States,3.7,GLOBE Observer App,null,null,null,false,,null,(source: camera),https://data.globe.gov/system/photos/2018/10/2...,null,null,null,null,null,null,null,null,null,null,null,null,(none),None,952,true,null,manual,2018-10-20 20:39:00.000,-609.7,25.8298,-80.1979,null,null,,false,,null,(source: camera),https://data.globe.gov/system/photos/2018/10/2...,false,false,,null,(source: camera),https://data.globe.gov/system/photos/2018/10/2...,false,null,null,null,48131703,,null,(source: camera),https://data.globe.gov/system/photos/2018/10/2...,17043304,United States of America Citizen Science,land_covers,139976,17RNJ803570,POINT (-80.1988 25.82908)
60898,USA,United States,1.7,GLOBE Data Entry Site Definition,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,None,20599,null,null,null,2018-08-07 14:14:33.585,None,None,None,M9,Urban,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,7908704,Walter C. Young Middle,land_covers,134661,Green Young Knights,POINT (-80.32215 26.0141)

In [41]:
fl_data = data[data["countryName"] == "United States"].copy()
fl_data = fl_data.cx[-87.7:-79.6, 24.4:31.1]  #FL bounding box
fl_data = fl_data.rename(columns={"siteId": "siteId"})

In [43]:
fl_data.shape

(625, 35)

In [44]:
merged = pd.merge(florida_only, fl_data, on="siteId")

In [45]:
merged.shape

(178, 97)

In [16]:
#urban=
#farmland=

SyntaxError: invalid syntax (ipython-input-3132458695.py, line 1)

In [35]:
merged

,countryCode_x,countryName_x,elevation_x,landcoversDataSource,landcoversDownwardCaption,landcoversDownwardExtraData,landcoversDownwardPhotoUrl,landcoversDryGround,landcoversEastCaption,landcoversEastClassifications,landcoversEastExtraData,landcoversEastPhotoUrl,landcoversFeature1Caption,landcoversFeature1ExtraData,landcoversFeature1PhotoUrl,landcoversFeature2Caption,landcoversFeature2ExtraData,landcoversFeature2PhotoUrl,landcoversFeature3Caption,landcoversFeature3ExtraData,landcoversFeature3PhotoUrl,landcoversFeature4Caption,landcoversFeature4ExtraData,landcoversFeature4PhotoUrl,landcoversFieldNotes,landcoversGlobeTeams,landcoversLandCoverId,landcoversLeavesOnTrees,landcoversLocationAccuracyM,landcoversLocationMethod,landcoversMeasuredAt,landcoversMeasurementElevation,landcoversMeasurementLatitude,landcoversMeasurementLongitude,landcoversMucCode,landcoversMucDescription,landcoversMucDetails,landcoversMuddy,landcoversNorthCaption,landcoversNorthClassifications,landcoversNorthExtraData,landcoversNorthPhotoUrl,landcoversRainingSnowing,landcoversSnowIce,landcoversSouthCaption,landcoversSouthClassifications,landcoversSouthExtraData,landcoversSouthPhotoUrl,landcoversStandingWater,landcoversUpwardCaption,landcoversUpwardExtraData,landcoversUpwardPhotoUrl,landcoversUserid,landcoversWestCaption,landcoversWestClassifications,landcoversWestExtraData,landcoversWestPhotoUrl,organizationId_x,organizationName_x,protocol_x,siteId,siteName_x,geometry_x,countryCode_y,countryName_y,elevation_y,mosquitohabitatmapperAbdomenCloseupPhotoUrls,mosquitohabitatmapperBreedingGroundEliminated,mosquitohabitatmapperComments,mosquitohabitatmapperDataSource,mosquitohabitatmapperExtraData,mosquitohabitatmapperGenus,mosquitohabitatmapperGlobeTeams,mosquitohabitatmapperLarvaFullBodyPhotoUrls,mosquitohabitatmapperLarvaeCount,mosquitohabitatmapperLastIdentifyStage,mosquitohabitatmapperLocationAccuracyM,mosquitohabitatmapperLocationMethod,mosquitohabitatmapperMeasuredAt,mosquitohabitatmapperMeasurementElevation,mosquitohabitatmapperMeasurementLatitude,mosquitohabitatmapperMeasurementLongitude,mosquitohabitatmapperMosquitoAdults,mosquitohabitatmapperMosquitoEggCount,mosquitohabitatmapperMosquitoEggs,mosquitohabitatmapperMosquitoHabitatMapperId,mosquitohabitatmapperMosquitoPupae,mosquitohabitatmapperSpecies,mosquitohabitatmapperUserid,mosquitohabitatmapperWaterSource,mosquitohabitatmapperWaterSourcePhotoUrls,mosquitohabitatmapperWaterSourceType,organizationId_y,organizationName_y,protocol_y,siteName_y,geometry_y
0,USA,United States,2.8,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2025/10/0...,false,null,"10% MUC 01 (b) [Trees, Closely Spaced, Evergre...",null,https://data.globe.gov/system/photos/2025/10/0...,null,null,null,null,null,null,null,null,null,null,null,null,House and yard on canal,None,86094,true,null,manual,2025-10-05 22:55:00,2,26.2152,-80.2169,M91,"Urban, Residential Property",,false,null,"10% MUC 02 (n) [Trees, Closely Spaced, Deciduo...",null,https://data.globe.gov/system/photos/2025/10/0...,false,false,null,"30% MUC 01 (b) [Trees, Closely Spaced, Evergre...",null,https://data.globe.gov/system/photos/2025/10/0...,false,null,null,https://data.globe.gov/system/photos/2025/10/0...,171829152,null,"10% MUC 01 (b) [Trees, Closely Spaced, Evergre...",null,https://data.globe.gov/system/photos/2025/10/0...,10532858,GLOBE Implementation Office GLOBE v-School,land_covers,400104,17RNJ782997,POINT (-80.21719 26.21473),USA,United States,2.8,null,false,Canal in City running from inland to ocean.,GLOBE Observer App,LarvaeVisibleNo,null,None,null,0,null,20,automatic,2025-10-08 12:15:00,0,26.2154,-80.2169,null,null,null,48840,false,null,171829152,"puddle or still water next to a creek, stream ...",null,flowing: still water found next to river or st...,10532858,GLOBE Implementation Office GLOBE v-School,mosquito_habitat_mapper,17RNJ782997,POINT (-80.21719 26.21473)
1,USA,United States,6.4,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2023/06/1...,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,null,null,null,null,null,null,null,null,null,null,null,null,This is in my backyard where I am doing my mos...,[SEES2023],59779,true,null,manual,2023-06-15 15:35:00,6,27.5877,-80.4441,null,null,,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,false,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,null,null,https://data.globe.gov/system/photos/2023/06/1...,106918405,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,17043304,United States of America Citizen Science,land_covers,317215,17RNL548516,POINT (-80.44476 27.58721),USA,United States,6.4,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,[SEES2023],null,31,identify,null,manual,2023-06-29 20:27:00,0,27.5877,-80.4438,null,null,null,43291,false,null,106918405,"cement, metal or plastic tank",https://data.globe.gov/system/photos/2023/06/2...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNL548516,POINT (-80.44476 27.58721)
2,USA,United States,6.4,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2023/06/1...,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,null,null,null,null,null,null,null,null,null,null,null,null,This is in my backyard where I am doing my mos...,[SEES2023],59779,true,null,manual,2023-06-15 15:35:00,6,27.5877,-80.4441,null,null,,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,false,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,null,null,https://data.globe.gov/system/photos/2023/06/1...,106918405,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,17043304,United States of America Citizen Science,land_covers,317215,17RNL548516,POINT (-80.44476 27.58721),USA,United States,6.4,null,true,null,GLOBE Observer App,LarvaeVisibleNo,null,[SEES2023],null,0,null,null,manual,2023-06-22 19:17:00,0,27.5877,-80.4441,null,null,null,43207,false,null,106918405,"cement, metal or plastic tank",https://data.globe.gov/system/photos/2023/06/2...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNL548516,POINT (-80.44476 27.58721)
3,USA,United States,6.4,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2023/06/1...,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,null,null,null,null,null,null,null,null,null,null,null,null,This is in my backyard where I am doing my mos...,[SEES2023],59779,true,null,manual,2023-06-15 15:35:00,6,27.5877,-80.4441,null,null,,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,false,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,null,null,https://data.globe.gov/system/photos/2023/06/1...,106918405,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,17043304,United States of America Citizen Science,land_covers,317215,17RNL548516,POINT (-80.44476 27.58721),USA,United States,6.4,null,true,null,GLOBE Observer App,LarvaeVisibleNo,null,[SEES2023],null,0,null,null,manual,2023-06-22 19:16:00,0,27.5877,-80.4441,null,null,null,43206,false,null,106918405,"cement, metal or plastic tank",https://data.globe.gov/system/photos/2023/06/2...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNL548516,POINT (-80.44476 27.58721)
4,USA,United States,6.4,GLOBE Observer App,null,null,https://data.globe.gov/system/photos/2023/06/1...,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,null,null,null,null,null,null,null,null,null,null,null,null,This is in my backyard where I am doing my mos...,[SEES2023],59779,true,null,manual,2023-06-15 15:35:00,6,27.5877,-80.4441,null,null,,true,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,false,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,false,null,null,https://data.globe.gov/system/photos/2023/06/1...,106918405,null,null,null,https://data.globe.gov/system/photos/2023/06/1...,17043304,United States of America Citizen Science,land_covers,317215,17RNL548516,POINT (-80.44476 27.58721),USA,United States,6.4,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,[SEES2023],https://data.globe.gov/system/photos/2023/06/2...,21,identify-siphon-pecten,null,manual,2023-06-22 19:21:00,0,27.5877,-80.4441,null,null,null,43205,false,null,106918405,"cement, metal or plastic tank",https://data.globe.gov/system/photos/2023/06/2...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNL548516,POINT (-80.44476 27.58721)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,USA,United States,3.3,GLOBE Observer App,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,null,null,null,null,null,null,null,null,null,null,null,null,This is for a Mosquito mapper land cover,[SEES2019],26152,true,null,manual,2019-07-27 18:24:00,3.2,26.3345,-80.1144,null,null,,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,false,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,58004254,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,17043304,United States of America Citizen Science,land_covers,163669,17RNK883130,POINT (-80.11519 26.33422),USA,United States,3.3,null,false,This is for my experiment and used red food dy...,GLOBE Observer App,null,null,[SEES2019],null,0,identify,None,None,2019-08-02 22:50:00,0,26.3343,-80.1143,true,null,false,14718,false,null,58004254,jar,https://data.globe.gov/system/photos/2019/08/0...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNK883130,POINT (-80.11519 26.33422)
174,USA,United States,3.3,GLOBE Observer App,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,null,null,null,null,null,null,null,null,null,null,null,null,This is for a Mosquito mapper land cover,[SEES2019],26152,true,null,manual,2019-07-27 18:24:00,3.2,26.3345,-80.1144,null,null,,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,false,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,58004254,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,17043304,United States of America Citizen Science,land_covers,163669,17RNK883130,POINT (-80.11519 26.33422),USA,United States,3.3,null,false,This is for my experiment and used a orange co...,GLOBE Observer App,null,null,[SEES2019],null,0,identify,None,None,2019-08-02 22:46:00,0,26.3343,-80.1144,true,null,false,14715,false,null,58004254,jar,https://data.globe.gov/system/photos/2019/08/0...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNK883130,POINT (-80.11519 26.33422)
175,USA,United States,3.3,GLOBE Observer App,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,null,null,null,null,null,null,null,null,null,null,null,null,This is for a Mosquito mapper land cover,[SEES2019],26152,true,null,manual,2019-07-27 18:24:00,3.2,26.3345,-80.1144,null,null,,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,false,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,58004254,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,17043304,United States of America Citizen Science,land_covers,163669,17RNK883130,POINT (-80.11519 26.33422),USA,United States,3.3,null,false,This is for my experiment and used a black con...,GLOBE Observer App,null,null,[SEES2019],null,0,identify,None,None,2019-08-02 22:49:00,0,26.3343,-80.1143,true,null,false,14717,false,null,58004254,jar,https://data.globe.gov/system/photos/2019/08/0...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNK883130,POINT (-80.11519 26.33422)
176,USA,United States,3.3,GLOBE Observer App,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,null,null,null,null,null,null,null,null,null,null,null,null,This is for a Mosquito mapper land cover,[SEES2019],26152,true,null,manual,2019-07-27 18:24:00,3.2,26.3345,-80.1144,null,null,,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,false,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,58004254,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,17043304,United States of America Citizen Science,land_covers,163669,17RNK883130,POINT (-80.11519 26.33422),USA,United States,3.3,null,false,null,GLOBE Observer App,null,null,[SEES2019],null,0,identify,None,None,2019-07-31 14:04:00,0,26.3347,-80.1142,true,null,false,14663,false,null,58004254,"puddle, vehhicle or animal tracks",null,still: lake/pond/swamp,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNK883130,POINT (-80.11519 26.33422)
177,USA,United States,3.3,GLOBE Observer App,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,null,null,null,null,null,null,null,null,null,null,null,null,This is for a Mosquito mapper land cover,[SEES2019],26152,true,null,manual,2019-07-27 18:24:00,3.2,26.3345,-80.1144,null,null,,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,false,false,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,true,,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,58004254,,null,(source: camera),https://data.globe.gov/system/photos/2019/07/2...,17043304,United States of America Citizen Science,land_covers,163669,17RNK883130,POINT (-80.11519 26.33422),USA,United States,3.3,null,true,"There are no eggs or larvae, but there are adu...",GLOBE Observer App,null,null,[SEES2019],null,0,identify,None,None,2019-07-27 18:16:00,0,26.3346,-80.1144,true,null,false,14662,false,null,58004254,discarded: other,null,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,17RNK883130,POINT (-80.11519 26.33422)