In [7]:
import pandas as pd                           # For working with data
pd.set_option("display.max_columns", None)    # Lets us see all columns of the data instead of just a preview
import geopandas as gpd                       # For working with spatial data
import numpy as np                            # For working with numbers
import matplotlib.pyplot as plt               # For making graphs
from datetime import date                     # For formatting dates
from PIL import Image                         # For getting and displaying images from links
import requests                               # For getting information from links
from io import BytesIO                        # For working with types of input and output

Matplotlib is building the font cache; this may take a moment.
/Users/gabesantos/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [10]:
end_date = "2026-01-31"
data = gpd.read_file(f"https://api.globe.gov/search/v1/measurement/?protocols=mosquito_habitat_mapper&datefield=measuredDate&startdate=2018-01-01&enddate={end_date}&geojson=TRUE&sample=FALSE")

In [15]:
data.head()

,countryCode,countryName,elevation,mosquitohabitatmapperAbdomenCloseupPhotoUrls,mosquitohabitatmapperBreedingGroundEliminated,mosquitohabitatmapperComments,mosquitohabitatmapperDataSource,mosquitohabitatmapperExtraData,mosquitohabitatmapperGenus,mosquitohabitatmapperGlobeTeams,mosquitohabitatmapperLarvaFullBodyPhotoUrls,mosquitohabitatmapperLarvaeCount,mosquitohabitatmapperLastIdentifyStage,mosquitohabitatmapperLocationAccuracyM,mosquitohabitatmapperLocationMethod,mosquitohabitatmapperMeasuredAt,mosquitohabitatmapperMeasurementElevation,mosquitohabitatmapperMeasurementLatitude,mosquitohabitatmapperMeasurementLongitude,mosquitohabitatmapperMosquitoAdults,mosquitohabitatmapperMosquitoEggCount,mosquitohabitatmapperMosquitoEggs,mosquitohabitatmapperMosquitoHabitatMapperId,mosquitohabitatmapperMosquitoPupae,mosquitohabitatmapperSpecies,mosquitohabitatmapperUserid,mosquitohabitatmapperWaterSource,mosquitohabitatmapperWaterSourcePhotoUrls,mosquitohabitatmapperWaterSourceType,organizationId,organizationName,protocol,siteId,siteName,geometry
0,USA,United States,59.3,null,false,null,GLOBE Observer App,LarvaeVisibleNo,null,None,null,0,null,29,automatic,2026-01-31 00:31:00,0,32.7151,-117.1295,null,null,null,50487,false,null,178205484,tree holes,https://data.globe.gov/system/photos/2026/01/3...,container: natural,17043304,United States of America Citizen Science,mosquito_habitat_mapper,409674,11SMS878197,POINT (-117.13018 32.715)
1,USA,United States,5.9,null,false,null,GLOBE Observer App,LarvaeVisibleYes,null,None,null,null,identify-photo-larva,18,automatic,2026-01-30 22:21:00,0,21.319,-158.024,null,null,null,50486,false,null,178278578,"plant husk (areca, coconut etc)",pending approval,container: natural,17043304,United States of America Citizen Science,mosquito_habitat_mapper,409671,04QFJ012577,POINT (-158.02421 21.3184)
2,BRA,Brazil,13.0,null,true,null,GLOBE Observer App,LarvaeVisibleNo,null,"[COLUNanoII, COLUNSLZ]",null,0,null,13,automatic,2026-01-29 14:17:00,0,-2.5462,-44.3257,null,null,null,50378,false,null,137422345,other,https://data.globe.gov/system/photos/2026/01/2...,container: artificial,17459532,Brazil Citizen Science,mosquito_habitat_mapper,373830,23MNT749185,POINT (-44.32625 -2.54662)
3,THA,Thailand,146.9,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,None,null,null,identify,null,manual,2026-01-26 08:17:00,0,16.3629,103.4308,null,null,null,50369,false,null,178884320,other,null,container: artificial,48451737,Anukoolnaree School,mosquito_habitat_mapper,409216,48QUD323097,POINT (103.42989 16.36267)
4,THA,Thailand,7.0,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,[GLOBE PCSHSTrang],null,30,identify-later,null,manual,2026-01-26 07:45:00,0,7.5552,99.5567,true,null,false,50360,true,null,132602739,tire,https://data.globe.gov/system/photos/2026/01/2...,container: artificial,163028,Princess Chulabhorn Science High School Trang,mosquito_habitat_mapper,210710,47NNJ614351,POINT (99.55658 7.55462)

In [13]:
#data.head()
data.shape

(47394, 35)

In [16]:
data.columns

Index(['countryCode', 'countryName', 'elevation',
       'mosquitohabitatmapperAbdomenCloseupPhotoUrls',
       'mosquitohabitatmapperBreedingGroundEliminated',
       'mosquitohabitatmapperComments', 'mosquitohabitatmapperDataSource',
       'mosquitohabitatmapperExtraData', 'mosquitohabitatmapperGenus',
       'mosquitohabitatmapperGlobeTeams',
       'mosquitohabitatmapperLarvaFullBodyPhotoUrls',
       'mosquitohabitatmapperLarvaeCount',
       'mosquitohabitatmapperLastIdentifyStage',
       'mosquitohabitatmapperLocationAccuracyM',
       'mosquitohabitatmapperLocationMethod',
       'mosquitohabitatmapperMeasuredAt',
       'mosquitohabitatmapperMeasurementElevation',
       'mosquitohabitatmapperMeasurementLatitude',
       'mosquitohabitatmapperMeasurementLongitude',
       'mosquitohabitatmapperMosquitoAdults',
       'mosquitohabitatmapperMosquitoEggCount',
       'mosquitohabitatmapperMosquitoEggs',
       'mosquitohabitatmapperMosquitoHabitatMapperId',
       'mosquitohabitatmapperMosquitoPupae', 'mosquitohabitatmapperSpecies',
       'mosquitohabitatmapperUserid', 'mosquitohabitatmapperWaterSource',
       'mosquitohabitatmapperWaterSourcePhotoUrls',
       'mosquitohabitatmapperWaterSourceType', 'organizationId',
       'organizationName', 'protocol', 'siteId', 'siteName', 'geometry'],
      dtype='object')

In [17]:
data.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 47394 entries, 0 to 47393
Data columns (total 35 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   countryCode                                    47308 non-null  object
 1   countryName                                    47308 non-null  object
 2   elevation                                      47394 non-null  object
 3   mosquitohabitatmapperAbdomenCloseupPhotoUrls   47394 non-null  object
 4   mosquitohabitatmapperBreedingGroundEliminated  47394 non-null  object
 5   mosquitohabitatmapperComments                  47394 non-null  object
 6   mosquitohabitatmapperDataSource                47394 non-null  object
 7   mosquitohabitatmapperExtraData                 47394 non-null  object
 8   mosquitohabitatmapperGenus                     47394 non-null  object
 9   mosquitohabitatmapperGlobeTeams                18001 non-null  object
 10  mosquitohabitatmapperLarvaFullBodyPhotoUrls    47394 non-null  object
 11  mosquitohabitatmapperLarvaeCount               47394 non-null  object
 12  mosquitohabitatmapperLastIdentifyStage         47394 non-null  object
 13  mosquitohabitatmapperLocationAccuracyM         29053 non-null  object
 14  mosquitohabitatmapperLocationMethod            29053 non-null  object
 15  mosquitohabitatmapperMeasuredAt                47394 non-null  datetime64[ms]
 16  mosquitohabitatmapperMeasurementElevation      47377 non-null  object
 17  mosquitohabitatmapperMeasurementLatitude       47377 non-null  object
 18  mosquitohabitatmapperMeasurementLongitude      47377 non-null  object
 19  mosquitohabitatmapperMosquitoAdults            47394 non-null  object
 20  mosquitohabitatmapperMosquitoEggCount          47394 non-null  object
 21  mosquitohabitatmapperMosquitoEggs              47394 non-null  object
 22  mosquitohabitatmapperMosquitoHabitatMapperId   47394 non-null  object
 23  mosquitohabitatmapperMosquitoPupae             47394 non-null  object
 24  mosquitohabitatmapperSpecies                   47394 non-null  object
 25  mosquitohabitatmapperUserid                    47394 non-null  object
 26  mosquitohabitatmapperWaterSource               47394 non-null  object
 27  mosquitohabitatmapperWaterSourcePhotoUrls      47394 non-null  object
 28  mosquitohabitatmapperWaterSourceType           47394 non-null  object
 29  organizationId                                 47394 non-null  object
 30  organizationName                               47308 non-null  object
 31  protocol                                       47394 non-null  object
 32  siteId                                         47394 non-null  object
 33  siteName                                       47394 non-null  object
 34  geometry                                       47394 non-null  geometry
dtypes: datetime64[ms](1), geometry(1), object(33)
memory usage: 12.7+ MB

In [19]:
fl_data = data[data["countryName"] == "United States"].copy()
fl_data = fl_data.cx[-87:-79, 24:31]  #FL bounding box

In [20]:
fl_data

,countryCode,countryName,elevation,mosquitohabitatmapperAbdomenCloseupPhotoUrls,mosquitohabitatmapperBreedingGroundEliminated,mosquitohabitatmapperComments,mosquitohabitatmapperDataSource,mosquitohabitatmapperExtraData,mosquitohabitatmapperGenus,mosquitohabitatmapperGlobeTeams,mosquitohabitatmapperLarvaFullBodyPhotoUrls,mosquitohabitatmapperLarvaeCount,mosquitohabitatmapperLastIdentifyStage,mosquitohabitatmapperLocationAccuracyM,mosquitohabitatmapperLocationMethod,mosquitohabitatmapperMeasuredAt,mosquitohabitatmapperMeasurementElevation,mosquitohabitatmapperMeasurementLatitude,mosquitohabitatmapperMeasurementLongitude,mosquitohabitatmapperMosquitoAdults,mosquitohabitatmapperMosquitoEggCount,mosquitohabitatmapperMosquitoEggs,mosquitohabitatmapperMosquitoHabitatMapperId,mosquitohabitatmapperMosquitoPupae,mosquitohabitatmapperSpecies,mosquitohabitatmapperUserid,mosquitohabitatmapperWaterSource,mosquitohabitatmapperWaterSourcePhotoUrls,mosquitohabitatmapperWaterSourceType,organizationId,organizationName,protocol,siteId,siteName,geometry
941,USA,United States,14.0,null,true,null,GLOBE Observer App,LarvaeVisibleNo,null,None,null,0,null,23,automatic,2025-11-04 17:41:00,0,30.5089,-86.5028,null,null,null,49205,false,null,159641339,jar,https://data.globe.gov/system/photos/2025/11/0...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,403045,16REU477752,POINT (-86.50288 30.50815)
942,USA,United States,14.0,null,true,null,GLOBE Observer App,LarvaeVisibleNo,null,None,null,0,null,null,manual,2025-11-04 20:38:00,0,30.5088,-86.5028,null,null,null,49206,false,null,159641339,jar,https://data.globe.gov/system/photos/2025/11/0...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,403045,16REU477752,POINT (-86.50288 30.50815)
1282,USA,United States,2.8,null,false,Canal in City running from inland to ocean.,GLOBE Observer App,LarvaeVisibleNo,null,None,null,0,null,20,automatic,2025-10-08 12:15:00,0,26.2154,-80.2169,null,null,null,48840,false,null,171829152,"puddle or still water next to a creek, stream ...",null,flowing: still water found next to river or st...,10532858,GLOBE Implementation Office GLOBE v-School,mosquito_habitat_mapper,400104,17RNJ782997,POINT (-80.21719 26.21473)
3160,USA,United States,3.5,null,false,null,GLOBE Observer App,LarvaeVisibleNo,null,None,null,0,null,31,automatic,2025-03-12 18:24:00,0,28.3521,-80.6053,null,null,null,46774,false,null,148137248,plant clumps (bamboo etc),https://data.globe.gov/system/photos/2025/03/1...,container: natural,17043304,United States of America Citizen Science,mosquito_habitat_mapper,380362,17RNM386362,POINT (-80.60613 28.35146)
3171,USA,United States,43.6,null,true,null,GLOBE Observer App,LarvaeVisibleYes,null,None,null,12,identify,12,automatic,2025-03-07 18:41:00,0,28.2852,-81.6414,true,null,false,46775,true,null,36036190,estuary,null,flowing: still water found next to river or st...,10532858,GLOBE Implementation Office GLOBE v-School,mosquito_habitat_mapper,380476,17RMM371289,POINT (-81.64142 28.28463)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42490,USA,United States,25.4,null,true,null,GLOBE Observer App,null,null,None,null,3,identify,None,None,2018-12-29 22:41:00,0,28.1407,-82.4334,false,null,true,6222,false,null,51180976,animal trough or water bowl,null,container: artificial,51181115,Graves Elementary,mosquito_habitat_mapper,143718,17RLM592136,POINT (-82.4338 28.14052)
42491,USA,United States,25.4,null,true,null,GLOBE Observer App,null,null,None,null,null,null,None,None,2018-12-29 22:20:00,0,28.1408,-82.4336,null,null,null,6219,false,null,51228147,"puddle, vehhicle or animal tracks",https://data.globe.gov/system/photos/2018/12/2...,still: lake/pond/swamp,17043304,United States of America Citizen Science,mosquito_habitat_mapper,143719,17RLM592136,POINT (-82.4338 28.14052)
42494,USA,United States,25.4,null,false,null,GLOBE Observer App,null,null,None,null,null,null,None,None,2018-12-29 21:38:00,0,28.1411,-82.4335,null,null,null,6217,false,null,2521381,fountain or bird bath,null,container: artificial,394556,University Of Toledo,mosquito_habitat_mapper,143714,17RLM592136,POINT (-82.4338 28.14052)
42495,USA,United States,25.4,null,true,null,GLOBE Observer App,null,null,None,null,3,identify,None,None,2018-12-29 22:30:00,0,28.1408,-82.4334,false,null,true,6220,true,null,51180976,can or bottle,https://data.globe.gov/system/photos/2018/12/2...,container: artificial,51181115,Graves Elementary,mosquito_habitat_mapper,143718,17RLM592136,POINT (-82.4338 28.14052)
46844,USA,United States,5.9,null,true,null,GLOBE Observer App,null,null,None,null,null,null,None,None,2018-03-17 16:09:00,5.9,26.45808,-80.142329,null,null,null,1886,null,null,38752608,fountain or bird bath,https://data.globe.gov/system/photos/2018/03/1...,container: artificial,17043304,United States of America Citizen Science,mosquito_habitat_mapper,109708,17RNK855267,POINT (-80.14233 26.45808)